version: "3.8"

volumes:
  ghgtracker_data:

networks:
  ghgtracker_net:

services:
  postgres_db:
    image: postgres:latest
    container_name: ghgtracker_db
    env_file: ".env"
    restart: unless-stopped 
    ports:
      - "5432:5432"
    volumes:
      - ghgtracker_data:/var/lib/postgresql/data
    networks:
      - ghgtracker_net

  api:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/app
    depends_on:
      - postgres_db
    networks:
      - ghgtracker_net